Repository puppetlabs/puppetlabs-apt, pull requests merged in 2018-09, with the labels that each got.

#789 (FM-7316) - Implementation of the i18n process
  .fixtures.yml
  .rubocop.yml
  .rubocop_todo.yml
  .sync.yml
  Gemfile
  Rakefile
  lib/puppet/provider/apt_key/apt_key.rb
  lib/puppet/type/apt_key.rb
  locales/ja/puppetlabs-apt.po
  locales/puppetlabs-apt.pot
  manifests/backports.pp
  manifests/conf.pp
  manifests/init.pp
  manifests/key.pp
  manifests/params.pp
  manifests/pin.pp
  manifests/ppa.pp
  manifests/setting.pp
  manifests/source.pp
  metadata.json
  spec/acceptance/apt_key_provider_spec.rb
  spec/spec_helper_acceptance.rb
  tasks/init.rb
Labels: feature

#793 (FM-7348) - OS logic cleanup
  manifests/backports.pp
  spec/classes/apt_spec.rb
Labels: maintenance

#796 (MODULES-7827) - Update to i18n test logic to account for puppet 6
  spec/spec_helper_acceptance.rb
Labels: maintenance

#795 (MODULES-3307) - Auto update expired keys
  lib/puppet/provider/apt_key/apt_key.rb
  lib/puppet/type/apt_key.rb
  locales/puppetlabs-apt.pot
  manifests/key.pp
  spec/acceptance/apt_key_provider_spec.rb
  spec/defines/key_compat_spec.rb
  spec/defines/key_spec.rb
  spec/unit/puppet/type/apt_key_spec.rb
Labels: feature

#801 (MODULES-6408) - Fix dirmngr install failing
  manifests/init.pp
Labels: bugfix

#802 (maint) - Update docs to reflect changes in key.pp
  REFERENCE.md
Labels: maintenance

#798 pdksync - (MODULES-6805) metadata.json shows support for puppet 6
  metadata.json
Labels: feature

#806 Module Release Prep 6.1.0
  CHANGELOG.md
  metadata.json
Labels: maintenance
