Repository puppetlabs/puppetlabs-apt, pull requests merged in 2018-12, with the labels that each got.

#830 (MODULES-8326) - apt-transport-https not ensured properly
  manifests/source.pp
  spec/defines/source_spec.rb
Labels: bugfix

#831 (MODULES-8321) - Add manage_auth_conf parameter
  manifests/init.pp
  manifests/params.pp
  spec/classes/apt_spec.rb
Labels: feature

#828 (maint) Remove duplicated fact declarations
  spec/classes/apt_backports_spec.rb
  spec/classes/apt_spec.rb
  spec/classes/apt_update_spec.rb
  spec/defines/conf_spec.rb
  spec/defines/key_compat_spec.rb
  spec/defines/key_spec.rb
  spec/defines/pin_spec.rb
  spec/defines/ppa_spec.rb
  spec/defines/setting_spec.rb
  spec/defines/source_compat_spec.rb
  spec/defines/source_spec.rb
Labels: maintenance

#832 Add support for dist-upgrade & autoremove action
  spec/acceptance/init_task_spec.rb
  tasks/init.json
  tasks/init.rb
Labels: feature, needs-tests

#834 pdksync - pdksync_heads/master-0-gbf720df
  .gitattributes
  .pdkignore
  .puppet-lint.rc
  .travis.yml
  Rakefile
  metadata.json
  spec/default_facts.yml
  spec/spec_helper.rb
Labels: maintenance

#835 pdksync - (FM-7655) Fix rubygems-update for ruby < 2.3
  .travis.yml
  metadata.json
Labels: bugfix
