Repository puppetlabs/puppetlabs-apt, pull requests merged in 2018-08, with the labels that each got.

#780 (MODULES-7668) Remove support for Puppet 4.7
  metadata.json
Labels: backwards-incompatible

#781 pdksync - (MODULES-7658) use beaker3 in puppet-module-gems
  .sync.yml
  Gemfile
Labels: maintenance

#773 Introduce an Apt::Proxy type to validate the hash
  README.md
  manifests/init.pp
  types/proxy.pp
Labels: feature

#787 (MODULES-4439) - Adding new sources/PPAs README clarification
  README.md
Labels: maintenance

#788 (MODULES-1630) - Expanding source list fix to cover all needed versions
  manifests/ppa.pp
Labels: bugfix

#791 (FM-7320) - Removed assert_type statements
  manifests/key.pp
  spec/defines/key_compat_spec.rb
  spec/defines/key_spec.rb
Labels: maintenance
