Repository puppetlabs/puppetlabs-apt, pull requests merged in 2021-09, with the labels that each got.

#999 (maint) Set DEBIAN_FRONTEND=noninteractive on upgrade
  tasks/init.rb
Labels: maintenance

#1007 (MODULES-11173) Add per-host overrides for apt::proxy
  REFERENCE.md
  manifests/init.pp
  spec/classes/apt_spec.rb
  templates/proxy.epp
  types/proxy.pp
  types/proxy_per_host.pp
Labels: feature

#1008 pdksync - (IAC-1598) - Remove Support for Debian 8
  metadata.json
Labels: bugfix
