Repository puppetlabs/puppetlabs-apt, pull requests merged in 2022-03, with the labels that each got.

#1017 Use fact() function for all os.distro.* facts
  REFERENCE.md
  manifests/backports.pp
  manifests/ppa.pp
  manifests/source.pp
Labels: community

#1022 pdksync - (GH-iac-334) Remove Support for Ubuntu 16.04
  metadata.json
Labels: bugfix

#1023 pdksync - (GH-iac-334) Remove Support for Ubuntu 14.04
  metadata.json
Labels: bugfix

#1024 (GH-iac-334) Remove code specific to unsupported OSs
  manifests/params.pp
  manifests/source.pp
  provision.yaml
  spec/acceptance/apt_key_provider_spec.rb
  spec/classes/apt_backports_spec.rb
  spec/classes/apt_spec.rb
  spec/classes/apt_update_spec.rb
  spec/defines/conf_spec.rb
  spec/defines/key_compat_spec.rb
  spec/defines/key_spec.rb
  spec/defines/mark_spec.rb
  spec/defines/pin_spec.rb
  spec/defines/ppa_spec.rb
  spec/defines/setting_spec.rb
  spec/defines/source_compat_spec.rb
  spec/defines/source_spec.rb
  spec/unit/facter/apt_dist_has_updates_spec.rb
  spec/unit/facter/apt_dist_package_security_updates_spec.rb
  spec/unit/facter/apt_dist_package_updates_spec.rb
  spec/unit/facter/apt_dist_security_updates_spec.rb
  spec/unit/facter/apt_dist_updates_spec.rb
  spec/unit/facter/apt_has_updates_spec.rb
  spec/unit/facter/apt_package_security_updates_spec.rb
  spec/unit/facter/apt_package_updates_spec.rb
  spec/unit/facter/apt_security_updates_spec.rb
  spec/unit/facter/apt_updates_spec.rb
Labels: backwards-incompatible

#1025 pdksync - Add labeller and stale GHA workflows
  .github/workflows/labeller.yml
  .github/workflows/stale.yml
Labels: maintenance
