Repository puppetlabs/puppetlabs-apt, pull requests merged in 2022-08, with the labels that each got.

#1042 (GH-1038) add support for `check-valid-until` configuration
  REFERENCE.md
  manifests/source.pp
  spec/defines/source_spec.rb
Labels: feature

#1044 Release prep v8.5.0
  CHANGELOG.md
  metadata.json
Labels: maintenance

#1046 pdksync - (GH-cat-11) Certify Support for Ubuntu 22.04
  metadata.json
Labels: feature

#1051 Harden apt-mark defined type
  examples/mark.pp
  manifests/mark.pp
  spec/defines/mark_spec.rb
Labels: bugfix

#1050 Deal with net-ftp being unavailable
  lib/puppet/provider/apt_key/apt_key.rb
Labels: community

#1052 Harden PPA defined type
  examples/ppa.pp
  lib/facter/apt_sources.rb
  manifests/init.pp
  manifests/params.pp
  manifests/ppa.pp
  spec/defines/ppa_spec.rb
  spec/unit/facter/apt_sources_spec.rb
  templates/add-apt-repository.sh.epp
Labels: bugfix, backwards-incompatible

#1053 (GH-cat-9) Update module to match current syntax standard
  .puppet-lint.rc
  .sync.yml
  REFERENCE.md
  Rakefile
  manifests/backports.pp
  manifests/init.pp
  manifests/key.pp
  manifests/params.pp
  manifests/pin.pp
  manifests/ppa.pp
  manifests/setting.pp
  manifests/source.pp
  manifests/update.pp
  spec/classes/apt_update_spec.rb
Labels: bugfix

#1056 (GH-1055) Fix hardcoded cache path
  manifests/ppa.pp
  spec/defines/ppa_spec.rb
Labels: bugfix

#1058 (GH-1057) Regex fix to allow dotted resources
  manifests/ppa.pp
  spec/defines/ppa_spec.rb
Labels: bugfix
