Repository puppetlabs/puppetlabs-apt, pull requests merged in 2022-10, with the labels that each got.

#1065 pdksync - (CONT-130) Dropping Support for Debian 9
  metadata.json
Labels: bugfix, hacktoberfest

#1067 pdksync - (PDKSync) Removal of puppet_module_gems
  .devcontainer/README.md
  Gemfile
  Rakefile
  metadata.json
Labels: maintenance, hacktoberfest

#1069 Do not remove PPA sources.list.d files if purge is enabled
  manifests/ppa.pp
Labels: community
