Repository puppetlabs/puppetlabs-apt, pull requests merged in 2023-05, with the labels that each got.

#1104 (MODULES-10831) key is expired if all subkeys are expired
  lib/puppet/provider/apt_key/apt_key.rb
  spec/unit/puppet/provider/apt_key_spec.rb
Labels: bugfix, community

#1108 pdksync - (CONT-1001) Add litmus ~> 1.0
  Gemfile
Labels: maintenance

#1110 (CONT-581) Adding deferred function support for password field
  manifests/init.pp
  spec/classes/apt_spec.rb
  spec/defines/source_spec.rb
  templates/auth_conf.epp
Labels: feature
