Repository puppetlabs/puppetlabs-apt, pull requests merged in 2023-06, with the labels that each got.

#1113 (CONT-1028) puppetlabs/stdlib: Allow 9.x
  manifests/init.pp
  manifests/key.pp
  manifests/ppa.pp
  manifests/source.pp
  metadata.json
Labels: community

#1114 Require stdlib 9.0.0 or newer
  metadata.json
Labels: feature, community

#1112 Update CODEOWNERS
  CODEOWNERS
Labels: maintenance

#1117 (Maint) Cleaning up .sync.yml file + PDK update
  .gitignore
  .pdkignore
  .rubocop.yml
  .rubocop_todo.yml
  .sync.yml
  Gemfile
  Rakefile
  metadata.json
  spec/spec_helper.rb
Labels: maintenance

#1119 pdksync - (CONT-990) - Adding Community Pull Requests template
  .github/pull_request_template.md
Labels: maintenance
