Repository puppetlabs/puppetlabs-apt, pull requests merged in 2023-01, with the labels that each got.

#1082 fix typo in source.pp
  manifests/source.pp
Labels: community

#1081 fix: remove `apt::` prefix from fact variables
  manifests/update.pp
  spec/classes/apt_update_spec.rb
Labels: bugfix, community

#1075 Updated mark as title can contain dot (fixes #1074)
  manifests/mark.pp
  spec/defines/mark_spec.rb
Labels: community

#1085 (CONT-493) PPA validation adjustment
  manifests/ppa.pp
  spec/defines/ppa_spec.rb
Labels: bugfix

#1086 pdksync - (CONT-494) Pin github_changelog_generator and JSON gem versions
  .sync.yml
  Gemfile
  metadata.json
Labels: maintenance
