Repository puppetlabs/puppetlabs-apt, pull requests merged in 2023-11, with the labels that each got.

#1143 pdksync - [CAT-1541]: Adding github directory to pdkignore
  .pdkignore
Labels: maintenance

#1147 Allow passing all `keyring` params in `apt::source`
  REFERENCE.md
  manifests/keyring.pp
  manifests/source.pp
Labels: feature, community

#1146 keyring: rename parameters to remove redundancy
  REFERENCE.md
  manifests/keyring.pp
  manifests/source.pp
Labels: backwards-incompatible, community

#1142 Cleanup Debian 9 and Ubuntu pre-18.04 specialcases
  manifests/init.pp
  manifests/key.pp
  manifests/ppa.pp
  manifests/source.pp
  spec/defines/source_spec.rb
Labels: feature, community

#1145 pdksync - 'CAT-945 - Update README.md LICENSE'
  Gemfile
  README.md
Labels: maintenance

#1149 Cat 1608 pdk update
  .rubocop.yml
  .rubocop_todo.yml
  .sync.yml
  Gemfile
  Rakefile
  lib/puppet/provider/apt_key/apt_key.rb
  metadata.json
  spec/default_facts.yml
  spec/unit/puppet/provider/apt_key_spec.rb
Labels: maintenance
