Repository puppetlabs/puppetlabs-apt, pull requests merged in 2024-02, with the labels that each got.

#1141 pdksync - (CAT-1256) Roll out puppetlabs-puppet-lint and puppetlabs-rspec-puppet through spec_helper v7.0
  Gemfile
Labels: maintenance

#1164 release_prep: Use puppetlabs_spec_helper 7.x
  Gemfile
Labels: community

#1159 Support "hourly" and Integer as value for update frequency (fixes #1157)
  README.md
  REFERENCE.md
  manifests/init.pp
  manifests/update.pp
  spec/classes/apt_update_spec.rb
Labels: feature, community

#1162 Backports: add keyring support
  examples/backports.pp
  manifests/backports.pp
  spec/classes/apt_backports_spec.rb
Labels: feature, community
