Repository puppetlabs/puppetlabs-apt, pull requests merged in 2024-11, with the labels that each got.

#1204 Running autoremove in non-interactive mode
  tasks/init.rb
Labels: maintenance

#1208 apt::setting: Dont expect source/content when removing settings
  manifests/setting.pp
  spec/defines/setting_spec.rb
Labels: bugfix

#1188 backports: pin using codename on Debian
  manifests/backports.pp
  spec/classes/apt_backports_spec.rb
Labels: maintenance, community
